### ISSUE TITLE
[Bug] sprite.play_flipbook's complete_function parameter must be optional

### ISSUE THREAD

**Issue by afrokick** [astrochili/defold-annotations#2]
v1.5.0

`sprite.lua`:

```lua
...
---@param complete_function fun(self, message_id, message, sender))|nil function to ...
...
function sprite.play_flipbook(url, id, complete_function, play_properties) end
```

There is a redundant **)** character in the method description.

https://defold.com/ref/stable/sprite/#sprite.play_flipbook:url-id-[complete_function]-[play_properties]

**Comment by afrokick** [comment]
Sorry, seems like the issue in defold documentation)

**Comment by afrokick** [comment]
I'll ping you when https://github.com/defold/defold/pull/8036 will be merged

**Comment by astrochili** [comment]
Oh, thank you! Thought I'd catch them all at https://github.com/defold/defold/pull/7955m but not 😁.

**Comment by astrochili** [comment]
Updated the release zip-archive with manual fixes. Please check it out.

**Comment by afrokick** [comment]
Defold 1.6.0 released with a new fixed documentation! Thank you!
