### ISSUE TITLE
editor.lua in Release 1.9.6 is broken

### ISSUE THREAD

**Issue by elMuso** [astrochili/defold-annotations#7]
![image](https://github.com/user-attachments/assets/71a123fd-c538-41c7-ae1b-3af0d43eab98)

The new editor api currently stops compilation.

Compiles if lines 169-170 and 200 are changed from this
```lua
--Line 169
---@param ...commands string|nil bob commands, e.g. "resolve" or "build"
function editor.bob(options, ...commands) end
--Line 200
function editor.execute(command, ..., options) end
```

to this:
```lua
--Line 169
---@param ... string|nil bob commands, e.g. "resolve" or "build"
function editor.bob(options, ...) end
--Line 200
function editor.execute(command, options, ...) end
```

It compiles with the warnings of undefined.

**Comment by astrochili** [comment]
Thanks! Many things to patch I see.

Fixed! Just fetch the annotations again.
